### ISSUE TITLE
Cannot deliver presents 

### ISSUE THREAD

**Issue by williamhatcher** [Zerthick/Presents#1]
Versions:
JAVA 8
Minecraft: 1.12.2
Sponge: 1.12.2-7.1.0-BETA-5
Presents: 1.1.1

Log uploaded to this [gist](https://gist.github.com/williamhatcher/3dfce1a5644e74f6b4a84c8f04af7971)

**Comment by Zerthick** [comment]
/facepalm  Yep, I know what's causing this, I'll release a patch.

**Comment by Zerthick** [comment]
Should be fixed in [v1.1.2](https://github.com/Zerthick/Presents/releases/tag/v1.1.2)!
